### ISSUE TITLE
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!

### ISSUE THREAD

**Issue by dorinvlas** [kyegomez/the-compiler#4]
`dorin@RO-6SBXTQ3:/mnt/c/Users/dorinvlas/Documents/AI Generated/the-compiler$ python3 the_compiler/the_compiler.py
Command output: Hello, World

Traceback (most recent call last):
  File "/mnt/c/Users/dorinvlas/Documents/AI Generated/the-compiler/the_compiler/the_compiler.py", line 357, in <module>
    solution = compiler.compile(input_spec, k, T, b, vth, timeout, confidence_threshold=confidence, max_iterations=max_iterations, convergence_threshold=convergence_threshold, convergence_count=convergence_count)
  File "/mnt/c/Users/dorinvlas/Documents/AI Generated/the-compiler/the_compiler/the_compiler.py", line 321, in compile
    translated_spec = self.spec_interpreter.translate(input_spec)
  File "/mnt/c/Users/dorinvlas/Documents/AI Generated/the-compiler/the_compiler/the_compiler.py", line 289, in translate
    translated_spec = self.LLM.generate_thoughts(prompt, 1)[0]
  File "/mnt/c/Users/dorinvlas/Documents/AI Generated/the-compiler/the_compiler/the_compiler.py", line 50, in generate_thoughts
    response = openai.Completion.create(
  File "/home/dorin/.local/lib/python3.10/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/dorin/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/dorin/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/dorin/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/home/dorin/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!`

OpenAI recommends this information to mitigate the ratelimit risk: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb

**Thanks @kyegomez and to all contributors for your efforts!

**Comment by kyegomez** [comment]
@dorinvlas 

Hey please excuse me for my late response, I am here for you.

I've just pushed a monumental update
